export const INCREMENT = 'INCREMENT'
export const RESET = 'RESET'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const SET_USER_INFO = 'SET_USER_INFO'

export const OS_NAME = 'OS_NAME'
export const SET_THEME = 'SET_THEME'
export const WINDOW_RESIZE = 'WINDOW_RESIZE'

export const SHOW_LOGIN_POPUP = 'SHOW_LOGIN_POPUP'
export const HIDE_LOGIN_POPUP = 'HIDE_LOGIN_POPUP'

export const PLAYING_GAME = 'PLAYING_GAME'
export const NO_PLAYING_GAME = 'NO_PLAYING_GAME'
export const TRIGGER_LOGIN = 'TRIGGER_LOGIN'
export const CLEAR_CALLBACK = 'CLEAR_CALLBACK'
export const SET_CALLBACK = 'SET_CALLBACK'

export const SHOW_FOOTER = 'SHOW_FOOTER'
export const PLAYING_GAME_APPID = 'PLAYING_GAME_APPID'
export const PLAYING_GAME_APPNAME = 'PLAYING_GAME_APPNAME'

export const RED_DOT_PUSH = 'RED_DOT_PUSH'
export const HOME_FOOTER_RED_DOT = 'HOME_FOOTER_RED_DOT'
export const GAME_FOOTER_RED_DOT = 'GAME_FOOTER_RED_DOT'
export const PERSONAL_FOOTER_RED_DOT = 'PERSONAL_FOOTER_RED_DOT'
export const COOKIE_HOME_BEST = 'COOKIE_HOME_BEST'
export const COOKIE_HOME_NEWS = 'COOKIE_HOME_NEWS'
export const COOKIE_PERSOANL_INFO = 'COOKIE_PERSOANL_INFO'
export const COOKIE_PERSOANL_SERVICE = 'COOKIE_PERSOANL_SERVICE'
export const COOKIE_GAME_HOT = 'COOKIE_GAME_HOT'
export const COOKIE_GAME_NEW = 'COOKIE_GAME_NEW'
export const COOKIE_HOME_INFO_NEWS = 'COOKIE_HOME_INFO_NEWS'
export const COOKIE_HOME_INFO_EVENT = 'COOKIE_HOME_INFO_EVENT'

export const ADD_PHOME_NEWS_PUSH_ID = 'ADD_PHOME_NEWS_PUSH_ID'
export const ADD_PHOME_BEST_PUSH_ID = 'ADD_PHOME_BEST_PUSH_ID'
export const ADD_PGAME_HOT_PUSH_ID = 'ADD_PGAME_HOT_PUSH_ID'
export const ADD_PGAME_BEST_PUSH_ID = 'ADD_PGAME_BEST_PUSH_ID'
export const ADD_PPERSOAN_INFO_PUSH_ID = 'ADD_PPERSOAN_INFO_PUSH_ID'
export const ADD_PPERSOAN_SERVICE_PUSH_ID = 'ADD_PPERSOAN_SERVICE_PUSH_ID'
export const ADD_PHOME_INFO_NEWS_PUSH_ID = 'ADD_PHOME_INFO_NEWS_PUSH_ID'
export const ADD_PHOME_INFO_EVENT_PUSH_ID = 'ADD_PHOME_INFO_EVENT_PUSH_ID'
export const IS_TIPS_COOKIE = 'IS_TIPS_COOKIE'
export const ACCOUNT_FREEZE = 'ACCOUNT_FREEZE'
export const USER_STATUS_FREEZE = 'USER_STATUS_FREEZE'
// 弹窗的显示与隐藏
export const IS_SHOW_POPUP = 'IS_SHOW_POPUP'
// 隐私政策的url
export const SET_PRIVACY_URL = 'SET_PRIVACY_URL'
// 游戏是否被强制旋转
export const IS_FORCED_CIRCLE = 'IS_FORCED_CIRCLE'
// 是否是从浮标进入客服
export const IS_FLOAT_SERVICE = 'IS_FLOAT_SERVICE'
// 浮标退出游戏的状态
export const IS_EXIT_GAME = 'IS_EXIT_GAME'
// 浮标确认离开游戏的状态
export const IS_LEAVE_GAME = 'IS_LEAVE_GAME'
// 用于储存离开游戏的路由
export const LEAVE_GAME_ROUTER = 'LEAVE_GAME_ROUTER'
// 是否是pc端发送的事件
export const IS_PC_POST_EVENT = 'IS_PC_POST_EVENT'
// 是否是推广分享渠道进入平台
export const IS_SHARE_CHANNEL = 'IS_SHARE_CHANNEL'
export const SHOW_SERVICE_DIOLAG = 'SHOW_SERVICE_DIOLAG'
export const SERVICE_QUERY_ID = 'SERVICE_QUERY_ID'
export const FROM_QR = 'FROM_QR'
export const NOT_FROM_QR = 'NOT_FROM_QR'

// 是否完成二次登录的状态
export const SET_RELOGIN_WATCH = 'SET_RELOGIN_WATCH'

// 红点操作
export const SET_RED_DOT = 'SET_RED_DOT'
export const SET_CURRENT_RED_DOT = 'SET_CURRENT_RED_DOT'
export const CLEAR_RED_DOT_FILTER = 'CLEAR_RED_DOT_FILTER'
